language:
  python
env:
   - ADDON_ID=service.script.hue
   - BRANCH=leiaa
     
# command to install dependencies
install: 
  - pip install kodi-addon-checker

script:
  - kodi-addon-checker --branch $BRANCH $ADDON_ID