language: python
branches:
  only:
  - develop
  - master
  - scenesupport
    
matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "2.7.10"
    - python: "2.7.11"
  allow_failures:
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "nightly"
   env:
     - ADDON_ID=service.script.huie
     - BRANCH=leia
     
# command to install dependencies
install: 
  - pip install kodi-addon-checker

script:
  - kodi-addon-checker --branch $BRANCH $ADDON_ID